# Generated by Django 3.2.6 on 2021-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210806_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='phone',
        ),
    ]
