# Generated by Django 3.2.6 on 2021-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_mobile_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
