# Generated by Django 3.2.6 on 2021-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
