# Generated by Django 3.2.6 on 2021-08-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forget_password',
        ),
    ]
