# Generated by Django 3.2.6 on 2021-08-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_readlist_shelflist_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelflist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
