# Generated by Django 3.2.6 on 2021-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210817_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
