# Generated by Django 3.2.6 on 2021-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descripiton',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
